$folder = 'c:\Users\ninja\Desktop\BTC---Company-internet-site-main\ModeStyle'

function Do-Replace($content, $pairs) {
    foreach ($p in $pairs) { $content = $content.Replace($p[0], $p[1]) }
    return $content
}

# ---- COMMON (all files) ----
$common = @(
  @('lang="ru"','lang="hu"'),
  @('>Компания<','>Cégünk<'),
  @('>Продукция<','>Termékek<'),
  @('>Услуги<','>Szolgáltatások<'),
  @('>Сервис<','>Szerviz<'),
  @('>Новости<','>Hírek<'),
  @('title="Вверх"','title="Fel"'),
  @('title="Вниз"','title="Le"'),
  @(' Вернуться к продукции',' Vissza a termékekhez'),
  @('Нужна консультация или коммерческое предложение?','Konzultációra vagy ajánlatra van szüksége?'),
  @('Отправьте нам запрос — мы подберём оптимальное решение для вашего производства.','Küldjön nekünk megkeresést — optimális megoldást kínálunk az Ön termelésének.'),
  @('>Отправить запрос<','>Ajánlatkérés<'),
  @('Отправить запрос<','>Ajánlatkérés<'),
  @('>Контакты<','>Kapcsolat<'),
  @('<h4>Продукция</h4>','<h4>Termékek</h4>'),
  @('<h4>Услуги &amp; Сервис</h4>','<h4>Szolgáltatások &amp; Szerviz</h4>'),
  @('>Запасные части и ТО<','>Alkatrészek és karbantartás<'),
  @('>Проектирование и подбор<','>Tervezés és kiválasztás<'),
  @('>Монтаж оборудования<','>Berendezések felszerelése<'),
  @('>Гарантийное обслуживание<','>Garanciális szerviz<'),
  @('>Расширенная гарантия до 5 лет<','>Kiterjesztett garancia 5 évig<'),
  @('<h4>О компании</h4>','<h4>A cégről</h4>'),
  @('AZS Engineering — инжиниринговая компания, специализирующаяся на поставке и проектировании компрессорных станций для всех отраслей промышленности.','Az AZS Engineering mérnöki vállalat, amely kompresszorállomások szállítására és tervezésére specializálódott az ipar minden ágában.'),
  @('Все права защищены','Minden jog fenntartva'),
  @('>Главная<','>Főoldal<'),
  @('<li><a href="product-1.html">Компрессоры до 20 bar</a></li>','<li><a href="product-1.html">Kompresszorok 20 bar-ig</a></li>'),
  @('<li><a href="product-2.html">Компрессоры до 100 bar</a></li>','<li><a href="product-2.html">Kompresszorok 100 bar-ig</a></li>'),
  @('<li><a href="product-3.html">Компрессоры до 500 bar</a></li>','<li><a href="product-3.html">Kompresszorok 500 bar-ig</a></li>'),
  @('<li><a href="product-4.html">Компрессоры для дыхания</a></li>','<li><a href="product-4.html">Légzési levegő kompresszorok</a></li>'),
  @('<li><a href="product-5.html">Технические и благородные газы</a></li>','<li><a href="product-5.html">Műszaki és nemesgázok</a></li>'),
  @('<li><a href="product-6.html">Взрывоопасные газы</a></li>','<li><a href="product-6.html">Robbanásveszélyes gázok</a></li>'),
  @('<li><a href="product-7.html">Безмасляные компрессоры</a></li>','<li><a href="product-7.html">Olajmentes kompresszorok</a></li>'),
  @('<li><a href="product-8.html">Генераторы азота &amp; кислорода</a></li>','<li><a href="product-8.html">Nitrogén- és oxigéngenerátorok</a></li>'),
  @('<li><a href="product-9.html">Системы подготовки и хранения</a></li>','<li><a href="product-9.html">Levegő- és gáztároló rendszerek</a></li>'),
  @('Давление рабочее','Munkanyomás'),
  @('Давление нагнетания','Nyomónyomás'),
  @('Производительность','Teljesítmény'),
  @('Охлаждение','Hűtés'),
  @('Привод','Meghajtás'),
  @('Мощность привода','Meghajtási teljesítmény'),
  @('Исполнение','Kivitel'),
  @('Рабочая среда','Munkakörnyezet'),
  @('Тип сжатия','Sűrítés típusa'),
  @('Сжимаемые газы','Sűríthető gázok'),
  @('Сжимаемый газ','Sűríthető gáz'),
  @('Воздушное, водяное','Levegős, vizes'),
  @('Воздушное, водяное, опционально с рекуперацией тепла','Levegős, vizes, opcionálisan hővisszanyeréssel'),
  @('Водяное, опционально воздушное','Vizes, opcionálisan levegős'),
  @('Воздушное','Levegős'),
  @('Водяное','Vizes'),
  @('Электрический','Villamos'),
  @('Электрический, асинхронный и на постоянных магнитах','Villamos, aszinkron és állandó mágneses'),
  @('Электрический, бензиновым двигателем','Villamos, benzinmotorral'),
  @('Электрический, с бензиновым двигателем','Villamos, benzinmotorral'),
  @('Тип привода','Meghajtás típusa'),
  @('Электрический, бензиновый, дизельный','Villamos, benzines, dízel'),
  @('Точка росы на выходе','Harmatpont a kimeneten'),
  @('Точка росы (атм.)','Harmatpont (atm.)'),
  @('Чистота азота','Nitrogén tisztaság'),
  @('Чистота кислорода','Oxigén tisztaság'),
  @('Концентрация O₂','O₂ koncentráció'),
  @('Качество воздуха','Levegőminőség'),
  @('Тип','Típus'),
  @('Технология','Technológia'),
  @('Применение','Felhasználás'),
  @('btn btn-active">Отправить запрос','btn btn-active">Ajánlatkérés'),
  @('btn btn-sm btn-active">Отправить запрос','btn btn-sm btn-active">Ajánlatkérés'),
  @('btn btn-active btn-lg">Отправить запрос','btn btn-active btn-lg">Ajánlatkérés'),
  @('>Контакты</','>Kapcsolat</'),
  @('btn">Контакты','btn">Kapcsolat')
)

# ---- INDEX.HTML specific ----
$idx = @(
  @('<title>AZS Engineering – Компрессорные решения для промышленности</title>','<title>AZS Engineering – Kompresszoros megoldások az ipar számára</title>'),
  @('content="AZS Engineering – компрессорное оборудование для всех отраслей промышленности"','content="AZS Engineering – kompresszorberendezések az ipar minden ágában"'),
  @('<h2>О Компании</h2>','<h2>A Cégről</h2>'),
  @('<h2>Продукция</h2>','<h2>Termékek</h2>'),
  @('<h2>Услуги</h2>','<h2>Szolgáltatások</h2>'),
  @('<h2>Сервис</h2>','<h2>Szerviz</h2>'),
  @('<h2>Новости</h2>','<h2>Hírek</h2>'),
  @('<h2 style="color:#fff;">Отправить запрос</h2>','<h2 style="color:#fff;">Ajánlatkérés</h2>'),
  @('<h2>Контакты</h2>','<h2>Kapcsolat</h2>'),
  @('<h1>Компрессорные решения<br>для всех отраслей промышленности</h1>','<h1>Kompresszoros megoldások<br>az ipar minden ágában</h1>'),
  @('<p>Компрессорное оборудование от европейских поставщиков с гарантией и качеством</p>','<p>Európai gyártóktól származó kompresszorberendezések garanciával és minőséggel</p>'),
  @('<h1>Проектирование и поставка<br>компрессорных станций под ключ</h1>','<h1>Kompresszorállomások tervezése<br>és kulcsrakész szállítása</h1>'),
  @('<p>От проектирования и подбора оборудования до монтажа и сервисного обслуживания</p>','<p>A berendezések tervezésétől és kiválasztásától a felszerelésen át a szervizszolgáltatásig</p>'),
  @('<h1>Компрессоры под все газы<br>и любое давление</h1>','<h1>Kompresszorok minden gázhoz<br>és nyomáshoz</h1>'),
  @('<p>Воздух, азот, гелий, водород, кислород, биогаз — решения для любых задач промышленного сжатия</p>','<p>Levegő, nitrogén, hélium, hidrogén, oxigén, biogáz — megoldások minden ipari sűrítési feladathoz</p>'),
  @('href="#contacts" class="btn">Связаться с нами','href="#contacts" class="btn">Kapcsolatfelvétel'),
  @('href="#request" class="btn btn-white">Опросный лист','href="#request" class="btn btn-white">Kérdőív'),
  @('<p>AZS Engineering имеет многолетний опыт в поставках и проектировании компрессорных станций. Мы представляем европейских производителей компрессорного оборудования, гарантирующих надёжность и качество.</p>','<p>Az AZS Engineering sokéves tapasztalattal rendelkezik kompresszorállomások szállítása és tervezése terén. Európai kompresszorberendezés-gyártókat képviselünk, akik megbízhatóságot és minőséget garantálnak.</p>'),
  @('<p>Компания AZS Engineering — инжиниринговая компания, основным направлением деятельности которой является проектирование и поставка оборудования сжатого воздуха и газов низкого и высокого давления, а также систем инертных газов.</p>','<p>Az AZS Engineering mérnöki vállalat, amelynek fő tevékenysége alacsony és magas nyomású sűrített levegő és gázberendezések, valamint semlegesgáz-rendszerek tervezése és szállítása.</p>'),
  @('<p>Компания имеет собственное производство, оснащённое всем необходимым для изготовления компрессорных станций, их испытаний, сервисного обслуживания и капитального ремонта. Персонал компании имеет многолетний опыт в реализации проектов различной сложности.</p>','<p>A vállalatnak saját gyártókapacitása van, amely felszerelt kompresszorállomások gyártásához, teszteléséhez, szervizéhez és nagyjavításához. A vállalat munkatársai sokéves tapasztalattal rendelkeznek különböző bonyolultságú projektek megvalósításában.</p>'),
  @('<p>Помимо стандартного компрессорного оборудования, наша компания готова разработать и предложить компрессорное оборудование или станции согласно техническим требованиям заказчика, включая контейнерные и мобильные компрессорные станции как с электроприводом, так и с дизельным приводом.</p>','<p>A szabványos kompresszorberendezések mellett vállalatunk kész az ügyfél műszaki követelményei szerint kompresszorberendezéseket vagy állomásokat tervezni és kínálni, beleértve a konténeres és mobil kompresszorállomásokat elektromos és dízel meghajtással egyaránt.</p>'),
  @('<p class="center" style="max-width:760px;margin:0 auto 40px;">Мы предлагаем надёжное и качественное компрессорное оборудование под воздух и все технические газы с любым давлением. Отправьте нам запрос и мы предложим Вам оптимальное решение по отношению цена/качество.</p>','<p class="center" style="max-width:760px;margin:0 auto 40px;">Megbízható és minőségi kompresszorberendezéseket kínálunk levegőhöz és minden műszaki gázhoz, bármilyen nyomáson. Küldjön nekünk megkeresést, és optimális ár/érték arányú megoldást javaslunk Önnek.</p>'),
  @('<h4><a href="product-1.html">Компрессоры до 20 bar</a></h4>','<h4><a href="product-1.html">Kompresszorok 20 bar-ig</a></h4>'),
  @('<li><a href="product-1.html#p1-1">Компрессоры поршневые</a></li>','<li><a href="product-1.html#p1-1">Dugattyús kompresszorok</a></li>'),
  @('<li><a href="product-1.html#p1-2">Компрессоры винтовые</a></li>','<li><a href="product-1.html#p1-2">Csavaros kompresszorok</a></li>'),
  @('<li><a href="product-1.html#p1-3">Компрессоры мобильные дизельные до 24 bar</a></li>','<li><a href="product-1.html#p1-3">Mobil dízel kompresszorok 24 bar-ig</a></li>'),
  @('<li><a href="product-1.html#p1-4">Компрессорные станции в контейнерно-блочном исполнении</a></li>','<li><a href="product-1.html#p1-4">Konténeres kompresszorállomások</a></li>'),
  @('<li><a href="product-1.html#p1-5">Компрессоры винтовые дожимные до 15 bar</a></li>','<li><a href="product-1.html#p1-5">Csavaros booszterkompresszorok 15 bar-ig</a></li>'),
  @('<h4><a href="product-2.html">Компрессоры до 100 bar</a></h4>','<h4><a href="product-2.html">Kompresszorok 100 bar-ig</a></h4>'),
  @('<li><a href="product-2.html#p2-1">Компрессоры поршневые до 100 bar</a></li>','<li><a href="product-2.html#p2-1">Dugattyús kompresszorok 100 bar-ig</a></li>'),
  @('<li><a href="product-2.html#p2-2">Компрессоры винтовые до 35 bar</a></li>','<li><a href="product-2.html#p2-2">Csavaros kompresszorok 35 bar-ig</a></li>'),
  @('<li><a href="product-2.html#p2-3">Компрессоры мобильные дизельные до 24 bar</a></li>','<li><a href="product-2.html#p2-3">Mobil dízel kompresszorok 24 bar-ig</a></li>'),
  @('<li><a href="product-2.html#p2-4">Компрессоры для выдува ПЭТ до 45 bar</a></li>','<li><a href="product-2.html#p2-4">PET fúvókompresszorok 45 bar-ig</a></li>'),
  @('<li><a href="product-2.html#p2-5">Бустеры винтовые до 40 bar</a></li>','<li><a href="product-2.html#p2-5">Csavaros booszterek 40 bar-ig</a></li>'),
  @('<li><a href="product-2.html#p2-6">Бустеры поршневые</a></li>','<li><a href="product-2.html#p2-6">Dugattyús booszterek</a></li>'),
  @('<h4><a href="product-3.html">Компрессоры до 500 bar</a></h4>','<h4><a href="product-3.html">Kompresszorok 500 bar-ig</a></h4>'),
  @('<li><a href="product-3.html#p3-1">Компрессоры поршневые до 500 bar</a></li>','<li><a href="product-3.html#p3-1">Dugattyús kompresszorok 500 bar-ig</a></li>'),
  @('<li><a href="product-3.html#p3-2">Компрессоры мембранные до 1000 bar</a></li>','<li><a href="product-3.html#p3-2">Membrános kompresszorok 1000 bar-ig</a></li>'),
  @('<li><a href="product-3.html#p3-3">Бустеры газовые до 500 bar</a></li>','<li><a href="product-3.html#p3-3">Gázbooszterek 500 bar-ig</a></li>'),
  @('<li><a href="product-3.html#p3-4">Бустеры кислородные до 200 bar</a></li>','<li><a href="product-3.html#p3-4">Oxigénbooszterek 200 bar-ig</a></li>'),
  @('<h4><a href="product-4.html">Компрессоры воздуха для дыхания</a></h4>','<h4><a href="product-4.html">Légzési levegő kompresszorok</a></h4>'),
  @('<li><a href="product-4.html#p4-1">Компрессоры</a></li>','<li><a href="product-4.html#p4-1">Kompresszorok</a></li>'),
  @('<li><a href="product-4.html#p4-2">Станции Nitrox для дайвинга</a></li>','<li><a href="product-4.html#p4-2">Nitrox állomások búvároknak</a></li>'),
  @('<li><a href="product-4.html#p4-3">Блоки очистки и осушки воздуха</a></li>','<li><a href="product-4.html#p4-3">Levegőtisztító és szárító egységek</a></li>'),
  @('<li><a href="product-4.html#p4-4">Запасные части и расходные материалы</a></li>','<li><a href="product-4.html#p4-4">Alkatrészek és fogyóanyagok</a></li>'),
  @('<h4><a href="product-5.html">Компрессоры для технических и благородных газов</a></h4>','<h4><a href="product-5.html">Kompresszorok műszaki és nemesgázokhoz</a></h4>'),
  @('<li><a href="product-5.html#p5-1">Азот / Гелий / Аргон до 40 bar</a></li>','<li><a href="product-5.html#p5-1">Nitrogén / Hélium / Argon 40 bar-ig</a></li>'),
  @('<li><a href="product-5.html#p5-2">Азот / Гелий / Аргон до 450 bar</a></li>','<li><a href="product-5.html#p5-2">Nitrogén / Hélium / Argon 450 bar-ig</a></li>'),
  @('<li><a href="product-5.html#p5-3">Неон / Ксенон</a></li>','<li><a href="product-5.html#p5-3">Neon / Xenon</a></li>'),
  @('<li><a href="product-5.html#p5-4">CO / CO₂ до 19 bar</a></li>','<li><a href="product-5.html#p5-4">CO / CO₂ 19 bar-ig</a></li>'),
  @('<li><a href="product-5.html#p5-5">Мембранные компрессоры</a></li>','<li><a href="product-5.html#p5-5">Membrános kompresszorok</a></li>'),
  @('<h4><a href="product-6.html">Компрессоры для взрывоопасных газов</a></h4>','<h4><a href="product-6.html">Kompresszorok robbanásveszélyes gázokhoz</a></h4>'),
  @('<li><a href="product-6.html#p6-1">Природный газ / биогаз / синтетический газ до 450 bar</a></li>','<li><a href="product-6.html#p6-1">Földgáz / biogáz / szintetikus gáz 450 bar-ig</a></li>'),
  @('<li><a href="product-6.html#p6-2">Рекуперация бутан и пропан</a></li>','<li><a href="product-6.html#p6-2">Bután és propán visszanyerés</a></li>'),
  @('<li><a href="product-6.html#p6-3">Водород до 1000 bar</a></li>','<li><a href="product-6.html#p6-3">Hidrogén 1000 bar-ig</a></li>'),
  @('<li><a href="product-6.html#p6-4">Кислород до 250 bar</a></li>','<li><a href="product-6.html#p6-4">Oxigén 250 bar-ig</a></li>'),
  @('<h4><a href="product-7.html">Компрессоры безмасляные</a></h4>','<h4><a href="product-7.html">Olajmentes kompresszorok</a></h4>'),
  @('<li><a href="product-7.html#p7-1">Компрессоры поршневые до 15 bar</a></li>','<li><a href="product-7.html#p7-1">Dugattyús kompresszorok 15 bar-ig</a></li>'),
  @('<li><a href="product-7.html#p7-2">Компрессоры спиральные до 10 bar</a></li>','<li><a href="product-7.html#p7-2">Spirális kompresszorok 10 bar-ig</a></li>'),
  @('<li><a href="product-7.html#p7-3">Винтовые «сухого сжатия» до 3,3 bar</a></li>','<li><a href="product-7.html#p7-3">Szárazsűrítéses csavaros 3,3 bar-ig</a></li>'),
  @('<li><a href="product-7.html#p7-4">Винтовые «сухого сжатия» до 10,5 bar</a></li>','<li><a href="product-7.html#p7-4">Szárazsűrítéses csavaros 10,5 bar-ig</a></li>'),
  @('<li><a href="product-7.html#p7-5">Винтовые с водяным впрыском до 14 bar</a></li>','<li><a href="product-7.html#p7-5">Vízinjektálású csavaros 14 bar-ig</a></li>'),
  @('<h4><a href="product-8.html">Генераторы азота &amp; кислорода</a></h4>','<h4><a href="product-8.html">Nitrogén- és oxigéngenerátorok</a></h4>'),
  @('<li><a href="product-8.html#p8-1">Мембранные N₂ до 99,5%</a></li>','<li><a href="product-8.html#p8-1">Membrános N₂ 99,5%-ig</a></li>'),
  @('<li><a href="product-8.html#p8-2">PSA генераторы N₂ до 99,9999%</a></li>','<li><a href="product-8.html#p8-2">PSA N₂ generátorok 99,9999%-ig</a></li>'),
  @('<li><a href="product-8.html#p8-3">PSA генераторы О₂ до 95%</a></li>','<li><a href="product-8.html#p8-3">PSA O₂ generátorok 95%-ig</a></li>'),
  @('<li><a href="product-8.html#p8-4">Бустеры для кислорода до 250 bar</a></li>','<li><a href="product-8.html#p8-4">Oxigénbooszterek 250 bar-ig</a></li>'),
  @('<li><a href="product-8.html#p8-5">Газ Nitrox до 40% кислорода</a></li>','<li><a href="product-8.html#p8-5">Nitrox gáz 40% oxigénig</a></li>'),
  @('<h4><a href="product-9.html">Системы подготовки и хранения воздуха и газов</a></h4>','<h4><a href="product-9.html">Levegő- és gázelőkészítő és tároló rendszerek</a></h4>'),
  @('<li><a href="product-9.html#p9-1">Сборки баллонов до 500 bar</a></li>','<li><a href="product-9.html#p9-1">Palackszerelvények 500 bar-ig</a></li>'),
  @('<li><a href="product-9.html#p9-2">Хранение кислорода до 250 bar</a></li>','<li><a href="product-9.html#p9-2">Oxigéntárolás 250 bar-ig</a></li>'),
  @('<li><a href="product-9.html#p9-3">Фильтры до 450 bar</a></li>','<li><a href="product-9.html#p9-3">Szűrők 450 bar-ig</a></li>'),
  @('<li><a href="product-9.html#p9-4">Осушители до 450 bar</a></li>','<li><a href="product-9.html#p9-4">Szárítók 450 bar-ig</a></li>'),
  @('<li><a href="product-9.html#p9-5">Конденсатоотводчики до 500 bar</a></li>','<li><a href="product-9.html#p9-5">Kondenzátelvezetők 500 bar-ig</a></li>'),
  @('<p class="center" style="max-width:700px;margin:0 auto 40px;">AZS Engineering осуществляет полный комплекс услуг по поставке, проектированию, монтажу и обслуживанию компрессорного оборудования.</p>','<p class="center" style="max-width:700px;margin:0 auto 40px;">Az AZS Engineering teljes körű szolgáltatásokat nyújt kompresszorberendezések szállítása, tervezése, felszerelése és karbantartása terén.</p>'),
  @('<h4>Запасные части и техническое обслуживание</h4>','<h4>Alkatrészek és műszaki karbantartás</h4>'),
  @('<h4>Проектирование и подбор оборудования</h4>','<h4>Berendezések tervezése és kiválasztása</h4>'),
  @('<h4>Пневмо- и энергоаудит компрессорных станций</h4>','<h4>Pneumatikai és energetikai audit kompresszorállomásokon</h4>'),
  @('<h4>Проведение дефектации компрессоров</h4>','<h4>Kompresszorok hibaelemzése</h4>'),
  @('<h4>Системы управления для многокомпрессорных станций</h4>','<h4>Vezérlőrendszerek többkompresszoros állomásokhoz</h4>'),
  @('<h4>Поиск и измерение утечек сжатого воздуха</h4>','<h4>Sűrített levegő szivárgásának keresése és mérése</h4>'),
  @('<h4>Монтаж оборудования и трубопроводов, шеф-монтаж</h4>','<h4>Berendezések és csővezetékek felszerelése, felügyeleti szerelés</h4>'),
  @('<h4>Система контроля качества сжатого воздуха</h4>','<h4>Sűrített levegő minőségellenőrző rendszer</h4>'),
  @('<h4>Обучение персонала по обслуживанию компрессоров</h4>','<h4>Személyzet képzése kompresszor-karbantartásban</h4>'),
  @('<span><i class="fa fa-check-circle"></i><span>Проведение технического обслуживания</span>','<span><i class="fa fa-check-circle"></i><span>Műszaki karbantartás elvégzése</span>'),
  @('<span>Проведение технического обслуживания</span>','<span>Műszaki karbantartás elvégzése</span>'),
  @('<span>Проведение ремонтных работ любой сложности</span>','<span>Javítási munkák elvégzése bármilyen bonyolultságban</span>'),
  @('<span>Проведение дефектации поршневых компрессоров и другого оборудования</span>','<span>Dugattyús kompresszorok és egyéb berendezések hibaelemzése</span>'),
  @('<span>Гарантийное обслуживание</span>','<span>Garanciális szerviz</span>'),
  @('<span>Производство запчастей по ТТХ заказчика (для оборудования снятого с производства)</span>','<span>Alkatrészek gyártása az ügyfél műszaki előírásai szerint (gyártásból kivont berendezésekhez)</span>'),
  @('<span>Предоставление расширенной гарантии до 5 лет</span>','<span>Kiterjesztett garancia nyújtása 5 évig</span>'),
  @('<span>Аренда компрессоров высокого давления</span>','<span>Nagynyomású kompresszorok bérbeadása</span>'),
  @('alt="Сервис и обслуживание"','alt="Szerviz és karbantartás"'),
  @('<h4 style="color:#d8a65f;margin-bottom:20px;">Загрузить опросный лист</h4>','<h4 style="color:#d8a65f;margin-bottom:20px;">Kérdőív letöltése</h4>'),
  @('"fa fa-download"></i> Опросный лист 1','"fa fa-download"></i> Kérdőív 1'),
  @('"fa fa-download"></i> Опросный лист 2','"fa fa-download"></i> Kérdőív 2'),
  @('<p style="color:rgba(255,255,255,.6);font-size:13px;margin-top:18px;">Заполните и отправьте опросный лист для получения коммерческого предложения.</p>','<p style="color:rgba(255,255,255,.6);font-size:13px;margin-top:18px;">Töltse ki és küldje el a kérdőívet az ajánlat kéréséhez.</p>'),
  @('placeholder="Имя"','placeholder="Név"'),
  @('placeholder="Компания"','placeholder="Cég"'),
  @('placeholder="Телефон"','placeholder="Telefon"'),
  @('placeholder="Ваш запрос / сообщение"','placeholder="Kérése / üzenete"'),
  @('<button type="submit" class="btn btn-active btn-lg">Отправить запрос</button>','<button type="submit" class="btn btn-active btn-lg">Ajánlatkérés</button>'),
  @('<h3>AZS Engineering</h3>','<h3>AZS Engineering</h3>'),
  @('<li>Словакия, Братислава</li>','<li>Szlovákia, Pozsony</li>'),
  @('<a href="#request" class="btn btn-active">Отправить запрос</a>','<a href="#request" class="btn btn-active">Ajánlatkérés</a>'),
  @('<a href="#contacts" class="btn">Контакты</a>','<a href="#contacts" class="btn">Kapcsolat</a>'),
  @('<a href="#request" class="btn btn-sm btn-active">Отправить запрос</a>','<a href="#request" class="btn btn-sm btn-active">Ajánlatkérés</a>'),
  @('<li><a href="#services">Запасные части и ТО</a></li>','<li><a href="#services">Alkatrészek és karbantartás</a></li>'),
  @('<li><a href="#services">Проектирование и подбор</a></li>','<li><a href="#services">Tervezés és kiválasztás</a></li>'),
  @('<li><a href="#services">Монтаж оборудования</a></li>','<li><a href="#services">Berendezések felszerelése</a></li>'),
  @('<li><a href="#services">Пневмо- и энергоаудит</a></li>','<li><a href="#services">Pneumatikai és energetikai audit</a></li>'),
  @('<li><a href="#servis">Гарантийное обслуживание</a></li>','<li><a href="#servis">Garanciális szerviz</a></li>'),
  @('<li><a href="#servis">Расширенная гарантия до 5 лет</a></li>','<li><a href="#servis">Kiterjesztett garancia 5 évig</a></li>'),
  @('<h4>Новости</h4>','<h4>Hírek</h4>'),
  @('>Подробнее<','>Részletek<')
)

# ---- PRODUCT-1 specific ----
$p1 = @(
  @('<title>Компрессоры до 20 bar – AZS Engineering</title>','<title>Kompresszorok 20 bar-ig – AZS Engineering</title>'),
  @('<h1>Компрессоры до 20 bar</h1>','<h1>Kompresszorok 20 bar-ig</h1>'),
  @('<li class="active">Компрессоры до 20 bar</li>','<li class="active">Kompresszorok 20 bar-ig</li>'),
  @('<h3>Компрессоры поршневые</h3>','<h3>Dugattyús kompresszorok</h3>'),
  @('<td>от 4 до 20 бар</td>','<td>4–20 bar</td>'),
  @('<td>от 190 л/мин до 2,5 м³/мин</td>','<td>190 l/perc–2,5 m³/perc</td>'),
  @('<td>Электрический, с бензиновым двигателем</td>','<td>Villamos, benzinmotorral</td>'),
  @('<td>От 1,0 до 15 кВт</td>','<td>1,0–15 kW</td>'),
  @('<td>На ресивере; с рефрижераторным, адсорбционным, мембранным осушителем; в шумопоглощающем корпусе</td>','<td>Tartállyal; hűtőszárítóval, adszorpciós, membránszárítóval; zajcsillapító burkolatban</td>'),
  @('<h3>Компрессоры винтовые</h3>','<h3>Csavaros kompresszorok</h3>'),
  @('<td>от 4 до 15 бар</td>','<td>4–15 bar</td>'),
  @('<td>от 0,3 до 55 м³/мин</td>','<td>0,3–55 m³/perc</td>'),
  @('<td>Электрический, асинхронный и на постоянных магнитах</td>','<td>Villamos, aszinkron és állandó mágneses</td>'),
  @('<td>От 2,2 до 355 кВт</td>','<td>2,2–355 kW</td>'),
  @('<td>С частотным регулированием; до 18,5 кВт на ресивере; с продлением гарантии до 5 лет</td>','<td>Frekvenciaszabályozással; 18,5 kW-ig tartállyal; garanciahosszabbítással 5 évig</td>'),
  @('<h3>Компрессоры мобильные дизельные до 24 bar</h3>','<h3>Mobil dízel kompresszorok 24 bar-ig</h3>'),
  @('<p>Мобильные компрессоры с дизельным приводом используются там, где есть необходимость в сжатом воздухе, но нет возможности подвести электропитание большой мощности. Применяются при строительных работах, для подачи сжатого воздуха на пневматический инструмент, для проведения испытаний и обжимки трубопроводов.</p>','<p>A dízel meghajtású mobil kompresszorokat ott alkalmazzák, ahol sűrített levegőre van szükség, de nagy teljesítményű elektromos áramellátás nem áll rendelkezésre. Építési munkáknál, pneumatikus szerszámok ellátásánál, csővezetékek tesztelésénél és préselésénél használják.</p>'),
  @('<p>Среди более чем 30 моделей мобильных компрессоров есть как небольшие одноосные модели, так и более мощные двуосные с уникальным поворотным механизмом на 180 градусов.</p>','<p>A több mint 30 mobil kompresszormodell között megtalálhatók a kisebb egytengelyes modellek és az erősebb kéttengelyes modellek egyedi 180 fokos forgószerkezettel.</p>'),
  @('<td>от 7 до 24 бар</td>','<td>7–24 bar</td>'),
  @('<td>от 1,0 до 27 м³/мин</td>','<td>1,0–27 m³/perc</td>'),
  @('<td>Бензиновый Honda (до 1,4 м³/мин), дизельный Yanmar и Cummins</td>','<td>Honda benzines (1,4 m³/percig), Yanmar és Cummins dízel</td>'),
  @('<td>От 15,5 до 228 кВт</td>','<td>15,5–228 kW</td>'),
  @('<td>На шасси / на раме. Опционально: обогрев картера для холодного запуска, встроенный электрогенератор</td>','<td>Alvázra / keretre szerelve. Opcionálisan: forgattyúház-fűtés hideg indításhoz, beépített elektromos generátor</td>'),
  @('<h3>Компрессорные станции в контейнерно-блочном исполнении</h3>','<h3>Konténeres kompresszorállomások</h3>'),
  @('<p>Компрессорное оборудование может монтироваться в модульном исполнении для облегчения монтажа без возведения капитальных зданий, а также для возможного переноса компрессорной станции в другое место.</p>','<p>A kompresszorberendezés moduláris kivitelben szerelhető fel, hogy megkönnyítse a telepítést tőkeigényes épületek emelése nélkül, és lehetővé tegye a kompresszorállomás más helyre való áthelyezését.</p>'),
  @('<p>Внутри мобильного модуля размещается всё необходимое оборудование: компрессора, системы осушки и фильтрации, ресивера, а также необходимая вентиляция для охлаждения оборудования. Модульные компрессорные станции могут оснащаться системой управления и удалённого контроля.</p>','<p>A mobil modulban minden szükséges berendezés elhelyezhető: kompresszorok, szárítási és szűrési rendszerek, tartályok, valamint a berendezés hűtéséhez szükséges szellőztetés. A moduláris kompresszorállomások felszerelhetők vezérlő- és távirányítási rendszerrel.</p>'),
  @('<h3>Компрессоры винтовые дожимные до 15 bar</h3>','<h3>Csavaros booszterkompresszorok 15 bar-ig</h3>'),
  @('<td>Азот, гелий, воздух, биометан, природный газ</td>','<td>Nitrogén, hélium, levegő, biometán, földgáz</td>'),
  @('<td>до 15 бар</td>','<td>15 bar-ig</td>'),
  @('<td>от 0,0 до 2,0 бар</td>','<td>0,0–2,0 bar</td>'),
  @('Давление на всасе','Szívóoldali nyomás'),
  @('<td>до 50 м³/мин</td>','<td>50 m³/percig</td>'),
  @('<td>От 4,0 до 315 кВт</td>','<td>4,0–315 kW</td>'),
  @('<td>С частотным регулированием; с системой редуцирования давления газа на всасе; во взрывозащищённом исполнении</td>','<td>Frekvenciaszabályozással; gáznyomás-csökkentő rendszerrel a szívóoldalon; robbanásbiztos kivitelben</td>')
)

# ---- PRODUCT-2 specific ----
$p2 = @(
  @('<title>Компрессоры до 100 bar – AZS Engineering</title>','<title>Kompresszorok 100 bar-ig – AZS Engineering</title>'),
  @('<h1>Компрессоры до 100 bar</h1>','<h1>Kompresszorok 100 bar-ig</h1>'),
  @('<li class="active">Компрессоры до 100 bar</li>','<li class="active">Kompresszorok 100 bar-ig</li>'),
  @('<p class="sub-heading">Компрессоры</p>','<p class="sub-heading">Kompresszorok</p>'),
  @('<p class="sub-heading">Бустеры</p>','<p class="sub-heading">Booszterek</p>'),
  @('<h3>Компрессоры поршневые до 100 bar</h3>','<h3>Dugattyús kompresszorok 100 bar-ig</h3>'),
  @('<p>Компрессорные установки рассчитаны на продолжительную работу в тяжёлых климатических условиях, имеют высококачественные узлы и агрегаты, гарантирующие большой ресурс и надёжность. Оснащаются асинхронными двигателями класса эффективности не менее IE3.</p>','<p>A kompresszoregységek hosszan tartó munkavégzésre terveztek nehéz éghajlati körülmények között, kiváló minőségű csomópontokkal és aggregátokkal, amelyek nagy élettartamot és megbízhatóságot garantálnak. IE3 hatásfok-osztályú aszinkron motorokkal vannak felszerelve.</p>'),
  @('<td>Воздух, азот, гелий, биометан, природный газ</td>','<td>Levegő, nitrogén, hélium, biometán, földgáz</td>'),
  @('<td>до 100 бар</td>','<td>100 bar-ig</td>'),
  @('<td>до 400 м³/час</td>','<td>400 m³/óráig</td>'),
  @('<td>От 4,0 до 315 кВт</td>','<td>4,0–315 kW</td>'),
  @('<td>На раме, с контроллером. Опционально: в шумопоглощающем кожухе, с дизельным приводом, взрывобезопасное</td>','<td>Keretre szerelve, vezérlővel. Opcionálisan: zajcsillapító burkolatban, dízel meghajtással, robbanásbiztos kivitelben</td>'),
  @('<h3>Компрессоры винтовые до 35 bar</h3>','<h3>Csavaros kompresszorok 35 bar-ig</h3>'),
  @('<td>От 16 до 35 бар</td>','<td>16–35 bar</td>'),
  @('<td>до 33 м³/мин</td>','<td>33 m³/percig</td>'),
  @('<td>Водяное, опционально воздушное</td>','<td>Vizes, opcionálisan levegős</td>'),
  @('<td>От 132 до 280 кВт</td>','<td>132–280 kW</td>'),
  @('<td>В шумопоглощающем корпусе. Опционально: с рефрижераторным осушителем и фильтрацией воздуха до безмасляного</td>','<td>Zajcsillapító burkolatban. Opcionálisan: hűtőszárítóval és olajmentes levegőszűréssel</td>'),
  @('<h3>Компрессоры мобильные дизельные до 24 bar</h3>','<h3>Mobil dízel kompresszorok 24 bar-ig</h3>'),
  @('<p>Мобильные компрессоры с дизельным приводом — решение там, где нет возможности подвести электропитание. Применяются при строительных работах и испытаниях трубопроводов.</p>','<p>A dízel meghajtású mobil kompresszorok megoldást jelentenek ott, ahol nincs lehetőség elektromos áramellátásra. Építési munkáknál és csővezetékek tesztelésénél alkalmazzák.</p>'),
  @('<td>Дизельный Yanmar и Cummins</td>','<td>Yanmar és Cummins dízel</td>'),
  @('<td>От 15,5 до 228 кВт</td>','<td>15,5–228 kW</td>'),
  @('<h3>Компрессоры для выдува ПЭТ до 42 bar</h3>','<h3>PET fúvókompresszorok 42 bar-ig</h3>'),
  @('<p>Для автоматических и полуавтоматических линий выдува ПЭТ тары требуются большой объём безмасляного и осушенного сжатого воздуха с рабочим давлением 33–40 бар. Благодаря 2-х ступенчатому безмасляному сжатию с промежуточным охлаждением не требуется дорогостоящая очистка от примесей компрессорного масла.</p>','<p>Automatikus és félautomatikus PET-fúvósoroknál nagy mennyiségű olajmentes és szárított sűrített levegőre van szükség 33–40 bar munkanyomáson. A kétfokozatú olajmentes sűrítésnek közbülső hűtéssel köszönhetően nincs szükség drága kompresszoroolajtisztításra.</p>'),
  @('<td>От 20 до 42 бар</td>','<td>20–42 bar</td>'),
  @('<td>от 100 до 6000 м³/час</td>','<td>100–6000 m³/óra</td>'),
  @('<td>от 22 до 900 кВт</td>','<td>22–900 kW</td>'),
  @('<td>С насосным модулем, с циклонным сепаратором, с электрошкафом и контроллером</td>','<td>Szivattyúmodullal, ciklonszeparátorral, elektromos szekrénnyel és vezérlővel</td>'),
  @('<h3>Бустеры винтовые до 40 bar</h3>','<h3>Csavaros booszterek 40 bar-ig</h3>'),
  @('<td>Воздух, азот, гелий</td>','<td>Levegő, nitrogén, hélium</td>'),
  @('<td>От 20 до 40 бар</td>','<td>20–40 bar</td>'),
  @('<td>до 10,5 м³/мин</td>','<td>10,5 m³/percig</td>'),
  @('<td>Воздушное, опционально водяное</td>','<td>Levegős, opcionálisan vizes</td>'),
  @('<td>от 15 до 55 кВт</td>','<td>15–55 kW</td>'),
  @('<td>В шумопоглощающем корпусе. Опционально: с частотным регулированием, с рефрижераторным осушителем</td>','<td>Zajcsillapító burkolatban. Opcionálisan: frekvenciaszabályozással, hűtőszárítóval</td>'),
  @('<h3>Бустеры поршневые</h3>','<h3>Dugattyús booszterek</h3>'),
  @('<td>Воздух, азот</td>','<td>Levegő, nitrogén</td>'),
  @('<td>От 15 до 40 бар</td>','<td>15–40 bar</td>'),
  @('<td>до 10,0 м³/мин</td>','<td>10,0 m³/percig</td>'),
  @('<td>от 7,5 до 30 кВт</td>','<td>7,5–30 kW</td>')
)

# ---- PRODUCT-3 specific ----
$p3 = @(
  @('<title>Компрессоры до 500 bar – AZS Engineering</title>','<title>Kompresszorok 500 bar-ig – AZS Engineering</title>'),
  @('<h1>Компрессоры до 500 bar</h1>','<h1>Kompresszorok 500 bar-ig</h1>'),
  @('<li class="active">Компрессоры до 500 bar</li>','<li class="active">Kompresszorok 500 bar-ig</li>'),
  @('<p class="sub-heading">Компрессоры</p>','<p class="sub-heading">Kompresszorok</p>'),
  @('<p class="sub-heading">Бустеры</p>','<p class="sub-heading">Booszterek</p>'),
  @('<h3>Компрессоры поршневые до 500 bar</h3>','<h3>Dugattyús kompresszorok 500 bar-ig</h3>'),
  @('<p>Компрессорные установки рассчитаны на продолжительную работу в тяжёлых климатических условиях. Оснащаются асинхронными двигателями класса эффективности не менее IE3. Каждый компрессор оборудован системой управления, водомаслоотделителем, промежуточными охладителями и предохранительными клапанами после каждой ступени.</p>','<p>A kompresszoregységek hosszan tartó munkavégzésre terveztek nehéz éghajlati körülmények között. IE3 hatásfok-osztályú aszinkron motorokkal vannak felszerelve. Minden kompresszor vezérlőrendszerrel, víz-olajszeparátorral, közbenső hűtőkkel és biztonsági szelepekkel van ellátva minden fokozat után.</p>'),
  @('<td>Воздух, азот, гелий, биометан, природный газ</td>','<td>Levegő, nitrogén, hélium, biometán, földgáz</td>'),
  @('<td>до 400 бар (по запросу до 500 бар)</td>','<td>400 bar-ig (kérésre 500 bar-ig)</td>'),
  @('<td>до 1400 м³/час</td>','<td>1400 m³/óráig</td>'),
  @('<td>От 4,0 до 315 кВт</td>','<td>4,0–315 kW</td>'),
  @('<td>На раме, с контроллером. Опционально: в шумопоглощающем кожухе, с дизельным приводом, взрывобезопасное</td>','<td>Keretre szerelve, vezérlővel. Opcionálisan: zajcsillapító burkolatban, dízel meghajtással, robbanásbiztos kivitelben</td>'),
  @('<h3>Компрессоры мембранные до 1000 bar</h3>','<h3>Membrános kompresszorok 1000 bar-ig</h3>'),
  @('<p>Мембранные компрессоры — идеальное решение для сжатия газа без загрязнения. Применяются на химических заводах, нефтеперерабатывающих предприятиях, водородных заправочных станциях, для заправки кислородных баллонов в больницах.</p>','<p>A membrános kompresszorok ideális megoldást nyújtanak a gáz szennyezés nélküli sűrítéséhez. Vegyigyárakban, olajtimfinomítókban, hidrogén-töltőállomásokon és kórházi oxigénpalack-töltésre alkalmazzák.</p>'),
  @('<p><strong>Преимущества:</strong> отсутствие утечки газа, гарантированное отсутствие загрязнения, высокая безопасность при высоких давлениях, бесшумная работа, низкий уровень вибрации.</p>','<p><strong>Előnyök:</strong> gázszivárgás mentesség, garantált szennyezés mentesség, magas biztonság nagy nyomásokon, csendes működés, alacsony vibrációs szint.</p>'),
  @('<td>Безмасляное, объёмного типа. Рабочий элемент: металлическая мембрана</td>','<td>Olajmentes, volumetriás. Munkaelemek: fémlemez membrán</td>'),
  @('<td>до 1 000 бар</td>','<td>1 000 bar-ig</td>'),
  @('<td>до 500 Нм³/час</td>','<td>500 Nm³/óráig</td>'),
  @('<td>Воздух, водород, гелий, аргон, ксенон, этилен, фтор, сероводород, хлор, кислород</td>','<td>Levegő, hidrogén, hélium, argon, xenon, etilén, fluor, kénsav, klór, oxigén</td>'),
  @('<h3>Бустеры газовые до 500 bar</h3>','<h3>Gázbooszterek 500 bar-ig</h3>'),
  @('<p>Газовые бустеры предназначены для повышения давления различных технических газов. Широко применяются для заполнения баллонов высокого давления, тестирования оборудования и в промышленных процессах, требующих высокого давления газа.</p>','<p>A gázbooszterek különböző műszaki gázok nyomásának növelésére szolgálnak. Széleskörűen alkalmazzák nagynyomású palackok töltésére, berendezések tesztelésére és nagy gáznyomást igénylő ipari folyamatokban.</p>'),
  @('<h3>Бустеры кислородные до 200 bar</h3>','<h3>Oxigénbooszterek 200 bar-ig</h3>'),
  @('<p>Специализированные бустеры для работы с кислородом в безопасном исполнении. Применяются в медицине, металлургии и химической промышленности для повышения давления кислорода до 200 бар.</p>','<p>Speciális booszterek biztonságos kivitelben oxigénnel való munkához. Az orvostudományban, kohászatban és vegyiparban alkalmazzák az oxigén nyomásának 200 bar-ig való emelésére.</p>')
)

# ---- PRODUCT-4 specific ----
$p4 = @(
  @('<title>Компрессоры для дыхательного воздуха – AZS Engineering</title>','<title>Légzési levegő kompresszorok – AZS Engineering</title>'),
  @('<h1>Компрессоры воздуха для дыхания</h1>','<h1>Légzési levegő kompresszorok</h1>'),
  @('<li class="active">Компрессоры для дыхания</li>','<li class="active">Légzési levegő kompresszorok</li>'),
  @('<h3>Компрессоры дыхательного воздуха</h3>','<h3>Légzési levegő kompresszorok</h3>'),
  @('<p>Компрессоры дыхательного воздуха предназначены для заполнения баллонов для дыхания, которые используются пожарными, спасателями, водолазами и дайверами. Устанавливается специальная система фильтрации, обеспечивающая качество воздуха по стандарту DIN EN 12021.</p>','<p>A légzési levegő kompresszorok tűzoltók, mentők, búvárok és merülők légzőpalackjainak töltésére szolgálnak. Speciális szűrőrendszert telepítenek, amely biztosítja a DIN EN 12021 szabvány szerinti levegőminőséget.</p>'),
  @('<td>Поршневой, объёмного типа, маслозаполненный</td>','<td>Dugattyús, volumetriás, olajos</td>'),
  @('<td>от 160 до 400 бар</td>','<td>160–400 bar</td>'),
  @('<td>от 6 до 219 Нм³/час</td>','<td>6–219 Nm³/óra</td>'),
  @('<td>Электрический, бензиновый, дизельный</td>','<td>Villamos, benzines, dízel</td>'),
  @('<td>Остаточное масло: 0,5 мг/Нм³ · Точка росы: −70°С · CO₂ ≤ 0,1% · CO ≤ 8 мг/м³</td>','<td>Maradék olaj: 0,5 mg/Nm³ · Harmatpont: −70°C · CO₂ ≤ 0,1% · CO ≤ 8 mg/m³</td>'),
  @('<h3>Станции Nitrox для дайвинга</h3>','<h3>Nitrox állomások búvároknak</h3>'),
  @('<p>Газ нитрокс предназначен для расширения бездекомпрессионного лимита и уменьшения риска декомпрессионной болезни. Стандартные смеси: нитрокс-32 (EAN32 — 32% кислорода) и нитрокс-36 (EAN36 — 36% кислорода).</p>','<p>A nitrox gáz a dekompressziós korlát kiterjesztésére és a keszonbetegség kockázatának csökkentésére szolgál. Standard keverékek: nitrox-32 (EAN32 — 32% oxigén) és nitrox-36 (EAN36 — 36% oxigén).</p>'),
  @('<td>от 160 до 225 бар</td>','<td>160–225 bar</td>'),
  @('<td>до 40%</td>','<td>40%-ig</td>'),
  @('<td>−70°С</td>','<td>−70°C</td>'),
  @('<h3>Блоки очистки и осушки воздуха</h3>','<h3>Levegőtisztító és szárító egységek</h3>'),
  @('<p>Специализированные блоки очистки обеспечивают соответствие качества воздуха стандарту DIN EN 12021. Включают многоступенчатую фильтрацию масла, влаги, CO, CO₂ и других примесей. Подбираются под конкретный тип компрессора и условия эксплуатации.</p>','<p>A speciális tisztítóegységek biztosítják a levegőminőség megfelelőségét a DIN EN 12021 szabványnak. Tartalmazzák az olaj, nedvesség, CO, CO₂ és egyéb szennyeződések többlépéses szűrését. Konkrét kompresszortípushoz és üzemeltetési feltételekhez vannak kiválasztva.</p>'),
  @('<h3>Запасные части и расходные материалы</h3>','<h3>Alkatrészek és fogyóanyagok</h3>'),
  @('<p>Поставляем оригинальные запасные части и расходные материалы для всего ассортимента компрессоров дыхательного воздуха. Фильтрующие элементы, поглотители CO, клапаны, уплотнения — всё необходимое для технического обслуживания.</p>','<p>Eredeti alkatrészeket és fogyóanyagokat szállítunk a légzési levegő kompresszorok teljes választékához. Szűrőelemek, CO-elnyelők, szelepek, tömítések — minden szükséges a műszaki karbantartáshoz.</p>')
)

# ---- PRODUCT-5 specific ----
$p5 = @(
  @('<title>Компрессоры для технических и благородных газов – AZS Engineering</title>','<title>Kompresszorok műszaki és nemesgázokhoz – AZS Engineering</title>'),
  @('<h1>Компрессоры для технических и благородных газов</h1>','<h1>Kompresszorok műszaki és nemesgázokhoz</h1>'),
  @('<li class="active">Технические и благородные газы</li>','<li class="active">Műszaki és nemesgázok</li>'),
  @('<p class="sub-heading">Дожимные винтовые компрессоры</p>','<p class="sub-heading">Booszteres csavaros kompresszorok</p>'),
  @('<p class="sub-heading">Поршневые бустеры</p>','<p class="sub-heading">Dugattyús booszterek</p>'),
  @('<p class="sub-heading">Мембранные компрессоры</p>','<p class="sub-heading">Membrános kompresszorok</p>'),
  @('<h3>Азот / Гелий / Аргон до 40 bar</h3>','<h3>Nitrogén / Hélium / Argon 40 bar-ig</h3>'),
  @('<p>Дожимные винтовые компрессоры для технических и инертных газов (азот, гелий, аргон). Применяются для повышения давления на выходе криогенных установок, генераторов азота и сосудов низкого давления.</p>','<p>Booszteres csavaros kompresszorok műszaki és inert gázokhoz (nitrogén, hélium, argon). Kriogén berendezések, nitrogéngenerátorok és kis nyomású tartályok kimeneti nyomásának növelésére alkalmazzák.</p>'),
  @('<td>Азот, гелий, аргон</td>','<td>Nitrogén, hélium, argon</td>'),
  @('<td>до 40 бар</td>','<td>40 bar-ig</td>'),
  @('<td>Электрический</td>','<td>Villamos</td>'),
  @('<h3>Азот / Гелий / Аргон до 450 bar</h3>','<h3>Nitrogén / Hélium / Argon 450 bar-ig</h3>'),
  @('<p>Поршневые бустеры высокого давления для сжатия инертных газов. Применяются для заполнения баллонов высокого давления, испытаний и технологических процессов, требующих высокого давления.</p>','<p>Nagynyomású dugattyús booszterek inert gázok sűrítésére. Nagynyomású palackok töltésére, tesztelésre és nagy nyomást igénylő technológiai folyamatokban alkalmazzák.</p>'),
  @('<td>до 450 бар</td>','<td>450 bar-ig</td>'),
  @('<h3>Неон / Ксенон</h3>','<h3>Neon / Xenon</h3>'),
  @('<p>Специализированные компрессоры для редких и дорогостоящих благородных газов (неон, ксенон). Обеспечивают минимальные потери газа и полную герметичность системы. Применяются в производстве освещения, полупроводников и в аэрокосмической отрасли.</p>','<p>Speciális kompresszorok ritka és drága nemesgázokhoz (neon, xenon). Minimális gázveszteséget és teljes rendszertömítettséget biztosítanak. Világítóipari gyártásban, félvezető-iparban és az űriparban alkalmazzák.</p>'),
  @('<h3>CO / CO₂ до 19 bar</h3>','<h3>CO / CO₂ 19 bar-ig</h3>'),
  @('<p>Компрессоры и бустеры для сжатия CO и CO₂ в специальном исполнении с учётом токсичности и химической агрессивности этих газов. Применяются в пищевой промышленности, при производстве сварочных смесей, в химической отрасли.</p>','<p>Kompresszorok és booszterek CO és CO₂ sűrítésére speciális kivitelben, figyelembe véve ezen gázok toxicitását és kémiai agresszivitását. Az élelmiszeriparban, hegesztési keverékek gyártásánál és a vegyiparban alkalmazzák.</p>'),
  @('<td>CO, CO₂</td>','<td>CO, CO₂</td>'),
  @('<td>до 19 бар</td>','<td>19 bar-ig</td>'),
  @('<h3>Мембранные компрессоры</h3>','<h3>Membrános kompresszorok</h3>'),
  @('<p>Мембранные компрессоры предназначены для сжатия газов без смазки и загрязнения. Особенно подходят для сжатия чистых, взрывоопасных, токсичных и дорогостоящих газов.</p>','<p>A membrános kompresszorok kenés és szennyeződés nélküli gázsűrítésre szolgálnak. Különösen alkalmasak tiszta, robbanásveszélyes, mérgező és drága gázok sűrítésére.</p>'),
  @('<td>Безмасляное, объёмного типа. Металлическая мембрана</td>','<td>Olajmentes, volumetriás. Fémmembrán</td>'),
  @('<td>до 1 000 бар</td>','<td>1 000 bar-ig</td>'),
  @('<td>до 500 Нм³/час</td>','<td>500 Nm³/óráig</td>'),
  @('<td>Водород, гелий, аргон, ксенон, этилен, фтор, сероводород, хлор, кислород</td>','<td>Hidrogén, hélium, argon, xenon, etilén, fluor, kénhidrogén, klór, oxigén</td>')
)

# ---- PRODUCT-6 specific ----
$p6 = @(
  @('<title>Компрессоры для взрывоопасных газов – AZS Engineering</title>','<title>Kompresszorok robbanásveszélyes gázokhoz – AZS Engineering</title>'),
  @('<h1>Компрессоры для взрывоопасных газов</h1>','<h1>Kompresszorok robbanásveszélyes gázokhoz</h1>'),
  @('<li class="active">Взрывоопасные газы</li>','<li class="active">Robbanásveszélyes gázok</li>'),
  @('<p class="sub-heading">Винтовые компрессоры и бустеры</p>','<p class="sub-heading">Csavaros kompresszorok és booszterek</p>'),
  @('<p class="sub-heading">Поршневые компрессоры</p>','<p class="sub-heading">Dugattyús kompresszorok</p>'),
  @('<h3>Природный газ / биогаз / синтетический газ до 450 bar</h3>','<h3>Földgáz / biogáz / szintetikus gáz 450 bar-ig</h3>'),
  @('<p>Для заправки транспортных средств, работающих на природном газе, используются компактные компрессоры высокого давления. Разработаны для промышленного и бытового использования на небольших заправочных станциях.</p>','<p>Földgázon üzemelő járművek töltésére kompakt nagynyomású kompresszorokat alkalmaznak. Ipari és háztartási használatra tervezték kis töltőállomásokon.</p>'),
  @('<p>Все компрессоры для горючих газов изготовлены во взрывозащищённом исполнении в соответствии с директивой ATEX.</p>','<p>Az éghető gázokhoz készült összes kompresszor robbanásbiztos kivitelű az ATEX irányelvnek megfelelően.</p>'),
  @('<td>Природный газ, биогаз, синтетический газ</td>','<td>Földgáz, biogáz, szintetikus gáz</td>'),
  @('<td>до 450 бар</td>','<td>450 bar-ig</td>'),
  @('<td>Взрывозащищённое ATEX</td>','<td>Robbanásbiztos ATEX</td>'),
  @('<h3>Рекуперация бутана и пропана</h3>','<h3>Bután és propán visszanyerés</h3>'),
  @('<p>Компрессоры для рекуперации паров бутана и пропана на складах хранения сжиженного газа, нефтеперерабатывающих заводах и химических предприятиях. Работают во взрывозащищённом исполнении, обеспечивая безопасное сжатие и возврат испарённого газа.</p>','<p>Kompresszorok cseppfolyósított gáz raktárakban, olajtimfinomítókban és vegyipari üzemekben bután- és propángőz visszanyerésére. Robbanásbiztos kivitelben működnek, biztosítva az elpárolgott gáz biztonságos sűrítését és visszajuttatását.</p>'),
  @('<h3>Водород до 1000 bar</h3>','<h3>Hidrogén 1000 bar-ig</h3>'),
  @('<p>Компрессоры и бустеры для водорода — специальная серия оборудования для водородных заправочных станций, промышленных процессов и хранения водорода. Обеспечивают безопасное сжатие водорода до 1000 бар благодаря мембранной технологии и взрывозащищённому исполнению.</p>','<p>Hidrogén kompresszorok és booszterek — speciális berendezéssorozat hidrogén-töltőállomásokhoz, ipari folyamatokhoz és hidrogéntároláshoz. A membrántechnológia és a robbanásbiztos kivitel révén biztonságos hidrogénsűrítést biztosítanak 1000 bar-ig.</p>'),
  @('<td>Водород H₂</td>','<td>Hidrogén H₂</td>'),
  @('<td>до 1 000 бар</td>','<td>1 000 bar-ig</td>'),
  @('<td>Мембранный или поршневой (бустер)</td>','<td>Membrános vagy dugattyús (bőszter)</td>'),
  @('<h3>Кислород до 250 bar</h3>','<h3>Oxigén 250 bar-ig</h3>'),
  @('<p>Специализированные бустеры и компрессоры для кислорода с использованием материалов и смазок, совместимых с кислородной средой. Строгое соблюдение требований безопасности при работе с кислородом. Применяются в медицине, металлургии и химической промышленности.</p>','<p>Speciális booszterek és kompresszorok oxigénhez, oxigénkörnyezettel kompatibilis anyagok és kenőanyagok alkalmazásával. Az oxigénnel való munkavégzés biztonsági követelményeinek szigorú betartása. Az orvostudományban, kohászatban és a vegyiparban alkalmazzák.</p>'),
  @('<td>Кислород O₂</td>','<td>Oxigén O₂</td>'),
  @('<td>до 250 бар</td>','<td>250 bar-ig</td>')
)

# ---- PRODUCT-7 specific ----
$p7 = @(
  @('<title>Компрессоры безмасляные – AZS Engineering</title>','<title>Olajmentes kompresszorok – AZS Engineering</title>'),
  @('<h1>Компрессоры безмасляные</h1>','<h1>Olajmentes kompresszorok</h1>'),
  @('<li class="active">Компрессоры безмасляные</li>','<li class="active">Olajmentes kompresszorok</li>'),
  @('<p style="margin-bottom:30px;">В тех отраслях промышленности, где должны быть исключены все риски попадания смазки в пневмосистему, используются компрессоры безмасляного сжатия. Применяются в фармацевтической и пищевой промышленности, микроэлектронике, медицине и стоматологии.</p>','<p style="margin-bottom:30px;">Azokban az iparágakban, ahol ki kell zárni a kenőanyag pneumatikus rendszerbe kerülésének minden kockázatát, olajmentes sűrítésű kompresszorokat alkalmaznak. A gyógyszeriparban és élelmiszeriparban, mikroelektronikában, orvostudományban és fogászatban használják.</p>'),
  @('<h3>Компрессоры поршневые до 15 bar</h3>','<h3>Dugattyús kompresszorok 15 bar-ig</h3>'),
  @('<td>От 5 до 15 бар (есть модели до 30 бар)</td>','<td>5–15 bar (30 bar-ig terjedő modellek is)</td>'),
  @('<td>до 60,0 м³/час</td>','<td>60,0 m³/óráig</td>'),
  @('<td>от 150 Вт до 11 кВт</td>','<td>150 W–11 kW</td>'),
  @('<td>Опционально: с рефрижераторным, адсорбционным или мембранным осушителем, включая стерильные фильтры</td>','<td>Opcionálisan: hűtőszárítóval, adszorpciós vagy membránszárítóval, beleértve a steril szűrőket</td>'),
  @('<h3>Компрессоры спиральные до 10 bar</h3>','<h3>Spirális kompresszorok 10 bar-ig</h3>'),
  @('<p>Основная область применения — пищевая промышленность и фармацевтика.</p>','<p>Fő alkalmazási terület — élelmiszeripar és gyógyszeripar.</p>'),
  @('<td>от 2 до 10 бар</td>','<td>2–10 bar</td>'),
  @('<td>до 3,50 м³/мин</td>','<td>3,50 m³/percig</td>'),
  @('<td>от 1,5 до 30 кВт</td>','<td>1,5–30 kW</td>'),
  @('<h3>Винтовые «сухого сжатия» до 3,3 bar</h3>','<h3>Szárazsűrítéses csavaros 3,3 bar-ig</h3>'),
  @('<td>от 2 до 3,3 бар</td>','<td>2–3,3 bar</td>'),
  @('<td>от 24 до 72 м³/мин</td>','<td>24–72 m³/perc</td>'),
  @('<td>от 90 до 300 кВт</td>','<td>90–300 kW</td>'),
  @('<h3>Винтовые «сухого сжатия» до 10,5 bar</h3>','<h3>Szárazsűrítéses csavaros 10,5 bar-ig</h3>'),
  @('<td>от 5 до 10 бар</td>','<td>5–10 bar</td>'),
  @('<td>от 5,3 до 71,3 м³/мин</td>','<td>5,3–71,3 m³/perc</td>'),
  @('<td>от 45 до 450 кВт</td>','<td>45–450 kW</td>'),
  @('<h3>Винтовые с водяным впрыском до 14 bar</h3>','<h3>Vízinjektálású csavaros 14 bar-ig</h3>'),
  @('<p>Вместо масла в качестве смазки, охлаждения и уплотнения используется вода. Полностью безмасляный сжатый воздух на выходе без необходимости дополнительной очистки.</p>','<p>Kenés, hűtés és tömítés céljára olaj helyett vizet alkalmaznak. Teljesen olajmentes sűrített levegő a kimeneten, anélkül hogy további tisztításra lenne szükség.</p>'),
  @('<td>от 5 до 14 бар</td>','<td>5–14 bar</td>'),
  @('<td>от 3 до 20,7 м³/мин</td>','<td>3–20,7 m³/perc</td>'),
  @('<td>от 11 до 132 кВт</td>','<td>11–132 kW</td>')
)

# ---- PRODUCT-8 specific ----
$p8 = @(
  @('<title>Генераторы азота и кислорода – AZS Engineering</title>','<title>Nitrogén- és oxigéngenerátorok – AZS Engineering</title>'),
  @('<h1>Генераторы азота &amp; кислорода</h1>','<h1>Nitrogén- és oxigéngenerátorok</h1>'),
  @('<li class="active">Генераторы азота &amp; кислорода</li>','<li class="active">Nitrogén- és oxigéngenerátorok</li>'),
  @('<p class="sub-heading">Генераторы азота</p>','<p class="sub-heading">Nitrogéngenerátorok</p>'),
  @('<p class="sub-heading">Генераторы кислорода</p>','<p class="sub-heading">Oxigéngenerátorok</p>'),
  @('<p class="sub-heading">Генераторы Nitrox</p>','<p class="sub-heading">Nitrox generátorok</p>'),
  @('<h3>Мембранные генераторы N₂ до 99,5%</h3>','<h3>Membrános N₂ generátorok 99,5%-ig</h3>'),
  @('<p>Автономный генератор азота с электрическим приводом, производящий высококачественный сухой азот путём выделения азота из атмосферного воздуха с использованием мембранной технологии. Не требует регенерации, прост в обслуживании.</p>','<p>Villamos meghajtású önálló nitrogéngenerátor, amely kiváló minőségű száraz nitrogént állít elő az atmoszferikus levegőből nitrogén kinyerésével membránt technológia segítségével. Nem igényel regenerálást, könnyen karbantartható.</p>'),
  @('<td>7 − 350 (400) бар</td>','<td>7–350 (400) bar</td>'),
  @('<td>4,0 − 540 м³/час</td>','<td>4,0–540 m³/óra</td>'),
  @('<td>до 99,5%</td>','<td>99,5%-ig</td>'),
  @('<td>до −70°С</td>','<td>−70°C-ig</td>'),
  @('<h3>PSA генераторы N₂ до 99,9999%</h3>','<h3>PSA N₂ generátorok 99,9999%-ig</h3>'),
  @('<p>Генераторы азота на основе технологии PSA (Pressure Swing Adsorption) обеспечивают исключительно высокую чистоту азота — до 99,9999%. Применяются в электронной, химической, пищевой промышленности и металлургии, где требуется максимально чистый азот.</p>','<p>A PSA (Pressure Swing Adsorption) technológián alapuló nitrogéngenerátorok kivételesen magas nitrogéntisztaságot biztosítanak — 99,9999%-ig. Az elektronikai, vegyipari, élelmiszeriparban és kohászatban alkalmazzák, ahol maximálisan tiszta nitrogénre van szükség.</p>'),
  @('<td>Адсорбция при переменном давлении (PSA)</td>','<td>Váltónyomású adszorpció (PSA)</td>'),
  @('<td>до 99,9999% (6,0 ppm O₂)</td>','<td>99,9999%-ig (6,0 ppm O₂)</td>'),
  @('<h3>PSA генераторы О₂ до 95%</h3>','<h3>PSA O₂ generátorok 95%-ig</h3>'),
  @('<p>Генераторы кислорода на технологии PSA для медицинского и промышленного применения. Позволяют отказаться от закупки жидкого кислорода или кислородных баллонов, вырабатывая газ непосредственно на месте из атмосферного воздуха.</p>','<p>PSA technológiájú oxigéngenerátorok orvosi és ipari alkalmazásokhoz. Lehetővé teszik a folyékony oxigén vagy oxigénpalackok vásárlásának mellőzését, a helyszínen termelve a gázt az atmoszferikus levegőből.</p>'),
  @('<td>PSA (Pressure Swing Adsorption)</td>','<td>PSA (Pressure Swing Adsorption)</td>'),
  @('<td>до 95%</td>','<td>95%-ig</td>'),
  @('<h3>Бустеры для кислорода до 250 bar</h3>','<h3>Oxigénbooszterek 250 bar-ig</h3>'),
  @('<p>Специализированные поршневые бустеры для повышения давления кислорода. Используются в связке с PSA-генераторами или криогенными установками для заполнения баллонов высокого давления.</p>','<p>Speciális dugattyús booszterek oxigén nyomásának növelésére. PSA-generátorokkal vagy kriogén berendezésekkel együtt használják nagynyomású palackok töltéséhez.</p>'),
  @('<td>до 250 бар</td>','<td>250 bar-ig</td>'),
  @('<td>Кислород O₂</td>','<td>Oxigén O₂</td>'),
  @('<h3>Газ Nitrox до 40% кислорода</h3>','<h3>Nitrox gáz 40% oxigénig</h3>'),
  @('<p>Генераторы смеси нитрокс (обогащённый кислородом воздух) для дайвинг-центров и водолазных служб. Смешение воздуха с кислородом позволяет получить нитрокс EAN32 или EAN36 — стандартные смеси для технического и рекреационного дайвинга.</p>','<p>Nitrox keverék generátorok (oxigénnel dúsított levegő) merülőközpontok és búvárszolgálatok számára. A levegő és oxigén keveréke lehetővé teszi EAN32 vagy EAN36 nitrox előállítását — technikai és rekreációs merülés standard keverékei.</p>'),
  @('<td>21 — 40%</td>','<td>21–40%</td>'),
  @('<td>Дайвинг, водолазные работы</td>','<td>Merülés, búvármunkák</td>')
)

# ---- PRODUCT-9 specific ----
$p9 = @(
  @('<title>Системы подготовки и хранения воздуха и газов – AZS Engineering</title>','<title>Levegő- és gázelőkészítő és tároló rendszerek – AZS Engineering</title>'),
  @('<h1>Системы подготовки и хранения воздуха и газов</h1>','<h1>Levegő- és gázelőkészítő és tároló rendszerek</h1>'),
  @('<li class="active">Системы подготовки и хранения</li>','<li class="active">Levegő- és gáztároló rendszerek</li>'),
  @('<p class="sub-heading">Хранение воздуха и газов</p>','<p class="sub-heading">Levegő- és gáztárolás</p>'),
  @('<p class="sub-heading">Системы очистки и осушки</p>','<p class="sub-heading">Tisztítási és szárítási rendszerek</p>'),
  @('<h3>Сборки баллонов до 500 bar</h3>','<h3>Palackszerelvények 500 bar-ig</h3>'),
  @('<p>Модульные системы хранения — идеальное дополнение компрессорной системы. Обеспечивают краткосрочный отбор больших количеств воздуха и газа и постоянный объёмный поток. Системы хранения доступны для давлений 330, 350 и 400 бар.</p>','<p>A moduláris tárolórendszerek ideális kiegészítői a kompresszorrendszernek. Rövid ideig nagy mennyiségű levegő és gáz vételezését, valamint állandó volumetriás áramlást biztosítanak. A tárolórendszerek 330, 350 és 400 bar nyomáshoz érhetők el.</p>'),
  @('<td>до 500 бар</td>','<td>500 bar-ig</td>'),
  @('<td>Модульные сборки (2, 3, 6 баллонов и более)</td>','<td>Moduláris szerelvények (2, 3, 6 palack és több)</td>'),
  @('<h3>Хранение кислорода до 250 bar</h3>','<h3>Oxigéntárolás 250 bar-ig</h3>'),
  @('<p>Специализированные системы хранения кислорода в баллонах высокого давления. Изготовлены из материалов, совместимых с кислородной средой. Применяются в медицинских учреждениях, металлообработке и химической промышленности.</p>','<p>Speciális oxigéntároló rendszerek nagynyomású palackokban. Oxigénkörnyezettel kompatibilis anyagokból készültek. Orvosi intézményekben, fémfeldolgozásban és a vegyiparban alkalmazzák.</p>'),
  @('<td>до 250 бар</td>','<td>250 bar-ig</td>'),
  @('<td>Кислород O₂</td>','<td>Oxigén O₂</td>'),
  @('<h3>Фильтры до 450 bar</h3>','<h3>Szűrők 450 bar-ig</h3>'),
  @('<p>Высокоэффективные фильтры для очистки сжатого воздуха и газов от механических частиц, масляного аэрозоля, паров масла и микроорганизмов. Работают при давлениях до 450 бар, что делает их подходящими для применения в любых высокобарных системах.</p>','<p>Nagyhatékonyságú szűrők sűrített levegő és gázok tisztítására mechanikai részecskéktől, olajperméttől, olajgőztől és mikroorganizmusoktól. 450 bar-ig működnek, ami alkalmassá teszi őket bármilyen nagynyomású rendszerben való alkalmazásra.</p>'),
  @('<td>до 450 бар</td>','<td>450 bar-ig</td>'),
  @('<td>Механические частицы, масляный аэрозоль, пары масла, активированный уголь</td>','<td>Mechanikai részecskék, olajpermét, olajgőz, aktív szén</td>'),
  @('Степени фильтрации','Szűrési fokozatok'),
  @('<h3>Осушители рефрижераторные и адсорбционные до 450 bar</h3>','<h3>Hűtő- és adszorpciós szárítók 450 bar-ig</h3>'),
  @('<p>Рефрижераторные осушители охлаждают сжатый воздух/газ, конденсируя влагу, и обеспечивают точку росы до +3°С. Адсорбционные осушители обеспечивают точку росы до −70°С и применяются там, где требуется максимально сухой газ.</p>','<p>A hűtőszárítók lehűtik a sűrített levegőt/gázt, kondenzálva a nedvességet, és +3°C-ig biztosítják a harmatpontot. Az adszorpciós szárítók −70°C-ig biztosítják a harmatpontot, és ott alkalmazzák, ahol maximálisan száraz gázra van szükség.</p>'),
  @('<td>Рефрижераторный (до +3°С), адсорбционный (до −70°С)</td>','<td>Hűtő (+3°C-ig), adszorpciós (−70°C-ig)</td>'),
  @('<h3>Конденсатоотводчики до 500 bar и очистка конденсата от масла</h3>','<h3>Kondenzátelvezetők 500 bar-ig és kondenzát olajmentesítés</h3>'),
  @('<p>Автоматические конденсатоотводчики для надёжного удаления конденсата из сепараторов, ресиверов и осушителей. Системы очистки конденсата от масла позволяют утилизировать конденсат в соответствии с природоохранными нормами.</p>','<p>Automatikus kondenzátelvezetők a kondenzát megbízható eltávolítására szeparátorokból, tartályokból és szárítókból. A kondenzát olajmentesítő rendszerek lehetővé teszik a kondenzát ártalmatlanítását a környezetvédelmi előírásoknak megfelelően.</p>'),
  @('<td>Поплавковый, электронный (нулевые потери)</td>','<td>Úszós, elektronikus (nulla veszteség)</td>')
)

# Process files
$files = @(
  @{ name='index.html'; extra=$idx },
  @{ name='product-1.html'; extra=$p1 },
  @{ name='product-2.html'; extra=$p2 },
  @{ name='product-3.html'; extra=$p3 },
  @{ name='product-4.html'; extra=$p4 },
  @{ name='product-5.html'; extra=$p5 },
  @{ name='product-6.html'; extra=$p6 },
  @{ name='product-7.html'; extra=$p7 },
  @{ name='product-8.html'; extra=$p8 },
  @{ name='product-9.html'; extra=$p9 }
)

$enc = [System.Text.UTF8Encoding]::new($false)
foreach ($f in $files) {
    $path = Join-Path $folder $f.name
    $c = [System.IO.File]::ReadAllText($path, $enc)
    $c = Do-Replace $c $common
    $c = Do-Replace $c $f.extra
    [System.IO.File]::WriteAllText($path, $c, $enc)
    Write-Host "Done: $($f.name)"
}
Write-Host "All files translated."
